'use client';
import { useEffect, useMemo, useState } from 'react';
import { api, Brand, FinanceRequest, getRequestAccessToken, saveRequestAccessToken, getAuthRole, getSuperAdminToken, getSuperAdminEmail, getAuthUserId, getAuthUserName, clearSuperAdminSession } from '@/lib/api';
import { formatRupiah } from '@/utils/formatters';
import MoneyInput from '@/components/events/components/MoneyInput';
import { GAME_SUGGESTIONS,SLOT_OPTIONS,TOURNAMENT_SYSTEMS,QUICK_MONEY } from '@/constants/eventConstants';

type Kind='TOURNAMENT'|'SPONSOR'|'EVENT'|'EXPENSE'|'INCOME';
const labels:Record<Kind,string>={TOURNAMENT:'Registrasi Tournament',SPONSOR:'Pengajuan Sponsor',EVENT:'Pengajuan Membuat Acara',EXPENSE:'Pengajuan Pengeluaran',INCOME:'Pengajuan Pemasukan'};
const empty={brand_id:'',user_name:'',user_id:'',nama:'',game:'',kategori_event:'',sistem_turnamen:'Single Elimination',tanggal_mulai:'',tanggal_selesai:'',jumlah_peserta:'16',biaya_registrasi:'',target_pemasukan:'',budget:'',prize_pool:'',nominal:'',kategori:'',vendor:'',metode_pembayaran:'',catatan:''};

export default function RequestsPage(){
 const [kind,setKind]=useState<Kind>('TOURNAMENT'); const [form,setForm]=useState(empty); const [brands,setBrands]=useState<Brand[]>([]); const [rows,setRows]=useState<FinanceRequest[]>([]); const [status,setStatus]=useState<FinanceRequest|null>(null); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(false);
 useEffect(()=>{if(getAuthRole()!=='ADMIN'){location.href='/admin';return;}setForm(f=>({...f,user_name:getAuthUserName()||getSuperAdminEmail(),user_id:getAuthUserId()||getSuperAdminEmail()}));api.getBrands().then(setBrands).catch(()=>setBrands([])); const id=localStorage.getItem('tcc_last_request_id'); if(id && getRequestAccessToken()) api.getRequestStatus(id).then(setStatus).catch(()=>{});},[]);
 useEffect(()=>{if(!status||!['PENDING'].includes(status.status)||!status.request_id)return; const timer=window.setInterval(async()=>{try{const next=await api.getRequestStatus(status.request_id);setStatus(next); if(next.status==='APPROVED'&&next.whatsapp_url){window.clearInterval(timer); window.location.href=next.whatsapp_url;}}catch{}} ,5000); return()=>window.clearInterval(timer)},[status]);
 useEffect(()=>{if(getRequestAccessToken()) api.getRequests({},true).then(setRows).catch(()=>setRows([])); else setRows([])},[status]);
 const title=labels[kind];
 const set=(k:string)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(f=>({...f,[k]:e.target.value}));
 const setValue=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 async function submit(e:React.FormEvent){e.preventDefault();if(getAuthRole()!=='ADMIN'){location.href='/admin';return;}setLoading(true);setMsg('');try{const data:any={...form,type:kind,nominal:Number(form.nominal)||0,jumlah_peserta:Number(form.jumlah_peserta)||0,biaya_registrasi:Number(form.biaya_registrasi)||0,target_pemasukan:Number(form.target_pemasukan)||0,budget:Number(form.budget)||0,prize_pool:Number(form.prize_pool)||0};const r=await api.createRequest(data);localStorage.setItem('tcc_last_request_id',r.request_id);saveRequestAccessToken(r.request_access_token);setMsg(`Pengajuan ${title} berhasil dikirim. Status: MENUNGGU ACC.`);setForm(empty);const s=await api.getRequestStatus(r.request_id);setStatus(s)}catch(e){setMsg(e instanceof Error?e.message:'Gagal mengirim pengajuan')}finally{setLoading(false)}}
 const statusText=useMemo(()=>status?`${status.request_id} • ${status.status}`:'',[status]);
 return <div>
  <div className="page-header"><div><div className="eyebrow">Admin • Request Only</div><h1>Pusat Pengajuan</h1><p className="subtitle">Admin biasa hanya boleh mengajukan. Tidak ada edit/hapus transaksi dari sini.</p></div><div className="actions"><button className="btn secondary" onClick={()=>{clearSuperAdminSession();location.href="/admin"}}>Logout</button></div></div>
  {msg&&<div className="alert">{msg}</div>}
  {status&&<section className="section"><div className="section-head"><h2>Status pengajuan terakhir</h2><span className="tag">{status.status}</span></div><p><strong>{status.nama}</strong> — {statusText}</p>{status.status==='PENDING'&&<p className="muted">Menunggu Super Admin. Halaman akan mengecek status otomatis.</p>}{status.status==='APPROVED'&&status.whatsapp_url&&<button className="btn" onClick={()=>window.location.href=status.whatsapp_url}>Lanjut ke WhatsApp</button>}{status.status==='REJECTED'&&<p className="muted">Alasan: {status.rejection_reason||'Tidak dicantumkan.'}</p>}</section>}
  <section className="section"><div className="request-cards">{(Object.keys(labels) as Kind[]).map(k=><button key={k} className={`request-card ${kind===k?'selected':''}`} onClick={()=>setKind(k)}><strong>{labels[k]}</strong><span>{k==='TOURNAMENT'?'Ajukan ikut turnamen':k==='SPONSOR'?'Ajukan kerja sama sponsor':k==='EVENT'?'Minta persetujuan membuat acara':'Ajukan perubahan arus kas'}</span></button>)}</div></section>
  <section className="section"><div className="section-head"><h2>{title}</h2><span className="muted">Masuk PENDING → ACC Super Admin → WhatsApp</span></div>
   <form className="form-grid" onSubmit={submit}>
    <label>Brand<select value={form.brand_id} onChange={set('brand_id')} required><option value="">Pilih brand</option>{brands.map(b=><option key={b.brand_id} value={b.brand_id}>{b.nama_brand}</option>)}</select></label>
    <label>Pengaju<input value={form.user_name} readOnly/></label>
    <label className="wide">Judul / Nama pengajuan<input value={form.nama} onChange={set('nama')} required/></label>
    {(kind==='TOURNAMENT'||kind==='EVENT')&&<><label>Game<input list="request-game-suggestions" value={form.game} onChange={set('game')} placeholder="Ketik game…" required/><datalist id="request-game-suggestions">{GAME_SUGGESTIONS.map(g=><option key={g} value={g}/>)}</datalist></label><label>Kategori event<input value={form.kategori_event} onChange={set('kategori_event')} placeholder="Tournament / Fun Match / Scrim / Custom"/></label><label>Sistem turnamen<select value={form.sistem_turnamen} onChange={set('sistem_turnamen')} >{TOURNAMENT_SYSTEMS.map(x=><option key={x}>{x}</option>)}</select></label><label>Jumlah tim / peserta<select value={SLOT_OPTIONS.includes(Number(form.jumlah_peserta))?form.jumlah_peserta:'CUSTOM'} onChange={e=>setValue('jumlah_peserta',e.target.value==='CUSTOM'?'':e.target.value)}>{SLOT_OPTIONS.map(x=><option key={x} value={x}>{x} Tim</option>)}<option value="CUSTOM">Isi manual</option></select></label>{!SLOT_OPTIONS.includes(Number(form.jumlah_peserta))&&<label>Jumlah custom<input type="number" min="1" value={form.jumlah_peserta} onChange={set('jumlah_peserta')}/></label>}<label>Mulai<input type="date" value={form.tanggal_mulai} onChange={set('tanggal_mulai')} required/></label><label>Selesai<input type="date" value={form.tanggal_selesai} onChange={set('tanggal_selesai')} required/></label><MoneyInput label="Biaya registrasi" value={form.biaya_registrasi} onChange={v=>setForm(f=>({...f,biaya_registrasi:v}))} quick={QUICK_MONEY.registration}/><MoneyInput label="Budget" value={form.budget} onChange={v=>setForm(f=>({...f,budget:v}))} quick={QUICK_MONEY.budget}/><MoneyInput label="Prize pool" value={form.prize_pool} onChange={v=>setForm(f=>({...f,prize_pool:v}))} quick={QUICK_MONEY.prize}/></>}
    {kind==='SPONSOR'&&<><MoneyInput label="Nominal sponsor" value={form.nominal} onChange={v=>setValue('nominal',v)} quick={QUICK_MONEY.prize}/><label>Vendor/Perusahaan<input value={form.vendor} onChange={set('vendor')} /></label></>}
    {(kind==='EXPENSE'||kind==='INCOME')&&<><label>Kategori<input value={form.kategori} onChange={set('kategori')} placeholder="Ketik kategori…" required/></label><MoneyInput label="Nominal" value={form.nominal} onChange={v=>setValue('nominal',v)} quick={QUICK_MONEY.budget} required/><label>Vendor/Sumber<input value={form.vendor} onChange={set('vendor')} /></label><label>Metode pembayaran<input value={form.metode_pembayaran} onChange={set('metode_pembayaran')} /></label></>}
    <label className="wide">Catatan<textarea rows={4} value={form.catatan} onChange={set('catatan')}/></label>
    <div><button className="btn" disabled={loading}>{loading?'Mengirim…':'Kirim Pengajuan'}</button></div>
   </form>
  </section>
  <section className="section"><div className="section-head"><h2>Riwayat Pengajuan</h2><span className="muted">Read-only</span></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Jenis</th><th>Nama</th><th>Brand</th><th>Status</th><th>Dibuat</th></tr></thead><tbody>{rows.map(r=><tr key={r.request_id}><td>{r.request_id}</td><td>{labels[r.type]}</td><td>{r.nama}</td><td>{brands.find(b=>b.brand_id===r.brand_id)?.nama_brand||r.brand_id}</td><td><span className="tag">{r.status}</span></td><td>{r.created_at}</td></tr>)}{!rows.length&&<tr><td colSpan={6} className="empty muted">Belum ada pengajuan.</td></tr>}</tbody></table></div></section>
 </div>
}
