'use client';
import {useEffect,useMemo,useState} from 'react';import{api,Brand,getAuthRole}from'@/lib/api';
type Access=Record<string,any>;
const perms=[['view_cash','Lihat Kas'],['view_transactions','Lihat Transaksi'],['view_requests','Lihat Pengajuan'],['view_events','Lihat Event'],['view_reports','Lihat Report'],['create_request','Buat Pengajuan']];
export default function AccessControlPage(){const[role,setRole]=useState('');const[users,setUsers]=useState<Access[]>([]);const[brands,setBrands]=useState<Brand[]>([]);const[access,setAccess]=useState<Access[]>([]);const[selected,setSelected]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 async function load(){try{const[u,b,a]=await Promise.all([api.getUsers(),api.getBrands(),api.getBrandAccess()]);setUsers(u.filter(x=>String(x.role).toUpperCase()==='ADMIN'));setBrands(b);setAccess(a)}catch(e){setMsg(e instanceof Error?e.message:'Gagal memuat access control')}}
 useEffect(()=>{const r=getAuthRole();setRole(r);if(r==='SUPER_ADMIN')void load()},[]);
 const selectedUser=users.find(u=>String(u.id)===selected);const rows=useMemo(()=>brands.map(b=>{const x=access.find(a=>String(a.user_id)===selected&&String(a.brand_id)===String(b.brand_id));return {brand:b,record:x||{}}}),[brands,access,selected]);
 async function toggle(brandId:string,key:string,current:boolean){setBusy(true);try{await api.updateBrandAccess({user_id:selected,brand_id:brandId,[key]:!current,enabled:true});setMsg('Permission tersimpan.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Gagal menyimpan permission')}finally{setBusy(false)}}
 if(role!=='SUPER_ADMIN')return <div className="auth-wrap"><div className="auth-card"><div className="eyebrow">Restricted</div><h1>Super Admin Only</h1><p className="subtitle">Hanya Super Admin yang dapat mengatur akses Admin per brand.</p><button className="btn" onClick={()=>location.href='/super-admin'}>Login Super Admin</button></div></div>;
 return <div><div className="page-header"><div><div className="eyebrow">Security • RBAC</div><h1>Access Control</h1><p className="subtitle">Berikan akses per Admin dan per Brand. Super Admin selalu memiliki full access.</p></div></div>{msg&&<div className="alert">{msg}</div>}<section className="panel access-panel"><label>Pilih Admin<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Pilih akun Admin</option>{users.map(u=><option key={String(u.id)} value={String(u.id)}>{String(u.nama||u.email)} • {String(u.email)}</option>)}</select></label>{selectedUser&&<div className="access-summary"><b>{String(selectedUser.nama||selectedUser.email)}</b><span>Atur izin berdasarkan brand.</span></div>}</section>{selected&&<section className="section"><div className="access-list">{rows.map(({brand,record})=><div className="access-brand" key={brand.brand_id}><div><strong>{brand.nama_brand}</strong><span>{record.id?'Access configured':'Belum diberi akses'}</span></div><div className="permission-grid">{perms.map(([key,label])=>{const on=record[key]===true||String(record[key]).toUpperCase()==='TRUE'||record[key]===undefined&&!!record.id;return <button key={key} disabled={busy} className={`permission-chip ${on?'on':''}`} onClick={()=>void toggle(brand.brand_id,key,on)}><i>{on?'✓':'+'}</i>{label}</button>})}</div></div>)}</div></section>}</div>}
