'use client';
import { useEffect, useMemo, useState } from 'react';
import { api, getAuthRole } from '@/lib/api';
const perms=[['view_cash','Lihat Kas'],['view_transactions','Lihat Transaksi'],['view_events','Lihat Event'],['create_request','Buat Pengajuan'],['view_reports','Lihat Report']];
export default function AccessControlPage(){
 const [role,setRole]=useState(''); const [data,setData]=useState<any>(null); const [user,setUser]=useState(''); const [brand,setBrand]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 async function load(){try{setData(await api.getAccessControl())}catch(e){setMsg(e instanceof Error?e.message:'Gagal memuat Access Control')}}
 useEffect(()=>{const r=getAuthRole();setRole(r);if(r==='SUPER_ADMIN')void load()},[]);
 const current=useMemo(()=>data?.access?.find((x:any)=>String(x.user_id)===String(user)&&String(x.brand_id)===String(brand)),[data,user,brand]);
 useEffect(()=>{setSelected(current?.permissions||[])},[current?.id]);
 if(role!=='SUPER_ADMIN')return <div className="access-denied"><div className="eyebrow">Restricted</div><h1>Super Admin Only</h1><p>Access Control hanya dapat dibuka oleh Super Admin.</p></div>;
 async function save(){setBusy(true);setMsg('');try{await api.updateBrandAccess({user_id:user,brand_id:brand,permissions:selected});setMsg('Permission berhasil disimpan.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Gagal menyimpan')}finally{setBusy(false)}}
 return <div className="page-shell"><div className="page-header"><div><div className="eyebrow">Administration · Security</div><h1>Access Control</h1><p className="subtitle">Atur akses setiap Admin per brand. Kosongkan semua permission untuk mencabut akses.</p></div><span className="live-pill"><span className="status-dot"/> Super Admin · Full Access</span></div>
 {msg&&<div className="alert">{msg}</div>}
 <section className="access-layout"><div className="panel access-selector"><div className="eyebrow">01 · Select scope</div><h2>Pilih Admin & Brand</h2><label>Admin<select value={user} onChange={e=>setUser(e.target.value)}><option value="">Pilih admin</option>{(data?.users||[]).map((u:any)=><option key={u.id} value={u.id}>{u.email}</option>)}</select></label><label>Brand<select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">Pilih brand</option>{(data?.brands||[]).map((b:any)=><option key={b.brand_id} value={b.brand_id}>{b.nama_brand}</option>)}</select></label><div className="access-summary"><span>Scope</span><strong>{user&&brand?'Ready to configure':'Pilih keduanya'}</strong></div></div>
 <div className="panel access-permissions"><div className="eyebrow">02 · Permission matrix</div><h2>Feature Access</h2><div className="permission-list">{perms.map(([id,label])=><label className={`permission-row ${selected.includes(id)?'enabled':''}`} key={id}><span><b>{label}</b><small>{id}</small></span><input type="checkbox" checked={selected.includes(id)} disabled={!user||!brand} onChange={e=>setSelected(v=>e.target.checked?[...v,id]:v.filter(x=>x!==id))}/></label>)}</div><div className="permission-actions"><button className="btn secondary" onClick={()=>setSelected([])}>Revoke all</button><button className="btn" disabled={!user||!brand||busy} onClick={()=>void save()}>{busy?'Menyimpan…':'Simpan Permission'}</button></div></div></section>
 <section className="section"><div className="section-head"><div><div className="eyebrow">03 · Current access</div><h2>Access Matrix</h2></div><span className="muted">{data?.access?.length||0} assignment</span></div><div className="access-table">{(data?.access||[]).map((a:any)=><div className="access-matrix-row" key={a.id}><strong>{data.users?.find((u:any)=>String(u.id)===String(a.user_id))?.email||a.user_id}</strong><span>{data.brands?.find((b:any)=>String(b.brand_id)===String(a.brand_id))?.nama_brand||a.brand_id}</span><div>{(a.permissions||[]).map((p:string)=><span className="tag" key={p}>{p.replaceAll('_',' ')}</span>)}</div></div>)}{!data?.access?.length&&<div className="empty">Belum ada assignment. Admin baru tidak mendapatkan akses brand otomatis.</div>}</div></section></div>
}
