'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api, getAuthRole } from '@/lib/api';
import { formatRupiah } from '@/utils/formatters';
import Card from '@/components/common/Card';

function Landing(){
 const router=useRouter();
 const features=[['◈','Multi Brand Finance','Kelola kas, transaksi, dan event dari satu command center.'],['✓','Approval Control','Pengajuan admin dapat diverifikasi dan dikontrol Super Admin.'],['⌁','Live Analytics','Pantau cash flow, pemasukan, pengeluaran, dan performa event.'],['⌘','Secure Workspace','Akses Admin dibatasi per brand, Super Admin memiliki akses penuh.']];
 return <div className="landing-page">
  <header className="landing-nav"><a className="landing-brand" href="/"><span className="brand-mark">T</span><span><b>TCC FINANCE</b><small>Finance Command Center</small></span></a><div className="landing-nav-actions"><span className="landing-status"><i/> System ready</span><button className="btn secondary" onClick={()=>router.push('/admin')}>Admin Login</button><button className="btn" onClick={()=>router.push('/super-admin')}>Super Admin</button></div></header>
  <main>
   <section className="landing-hero"><div className="landing-copy"><span className="landing-kicker">TCC • FINANCE OPERATING SYSTEM</span><h1>Kelola <em>keuangan & event</em> tanpa kehilangan kendali.</h1><p>Satu workspace untuk multi-brand cash management, transaksi, pengajuan, event, approval, dan analytics.</p><div className="landing-cta"><button className="btn btn-lg" onClick={()=>router.push('/admin')}>Masuk ke Workspace <span>→</span></button><button className="btn secondary btn-lg" onClick={()=>document.getElementById('features')?.scrollIntoView({behavior:'smooth'})}>Jelajahi fitur</button></div><div className="landing-trust"><span><i/> Responsive</span><span><i/> Multi-brand</span><span><i/> Role-based</span><span><i/> Audit-ready</span></div></div><div className="landing-visual"><div className="visual-glow"/><div className="mock-window"><div className="mock-top"><span className="mock-dots"><i/><i/><i/></span><span>tcc.finance / command-center</span><b>LIVE</b></div><div className="mock-body"><div className="mock-title"><div><small>ALL BRANDS · CASH OVERVIEW</small><strong>Financial Command Center</strong></div><span>Aug 2026</span></div><div className="mock-metrics"><div><small>Total cash</small><strong>Rp8.500.000</strong><i>+12.4%</i></div><div><small>Income</small><strong>Rp12.500.000</strong><i>+8.1%</i></div><div><small>Expense</small><strong>Rp4.000.000</strong><i>-3.2%</i></div></div><div className="mock-chart"><div className="mock-chart-head"><span>Cash flow</span><span>Income · Expense</span></div><div className="mock-bars">{[38,54,43,72,60,86,68,94,78,88,74,98].map((h,i)=><span key={i} style={{height:`${h}%`}}/> )}</div></div><div className="mock-bottom"><span>MONGSTER <b>Rp1.000.000</b></span><span>TCC <b>Rp2.500.000</b></span><span>SHOCKWAVE <b>Rp5.000.000</b></span></div></div></div></div></section>
   <section id="features" className="landing-section"><div className="section-intro"><span className="landing-kicker">BUILT FOR OPERATIONS</span><h2>Satu sistem. Semua fungsi penting.</h2><p>Dirancang agar nyaman digunakan dari monitor besar sampai layar HP.</p></div><div className="feature-grid">{features.map(([icon,title,text])=><article className="feature-card" key={title}><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{text}</p><span className="feature-link">Explore →</span></article>)}</div></section>
   <section className="landing-showcase"><div><span className="landing-kicker">ROLE-BASED WORKSPACE</span><h2>Admin bekerja sesuai brand. Super Admin melihat semuanya.</h2><p>Permission dapat diatur per user dan per brand. Tidak perlu membuat sistem terpisah ketika organisasi berkembang.</p><div className="role-list"><span><b>SUPER ADMIN</b><small>Full access · All brands · Approval · Settings</small></span><span><b>ADMIN</b><small>Assigned brands · Requests · Events · Finance</small></span></div></div><div className="access-card"><div className="access-head"><span>Access Control</span><b>SECURE</b></div><div className="access-row"><span>Admin 01</span><span className="access-chip on">MONGSTER</span><span className="access-chip off">TCC</span></div><div className="access-row"><span>Admin 02</span><span className="access-chip off">MONGSTER</span><span className="access-chip on">TCC</span></div><div className="access-row"><span>Super Admin</span><span className="access-chip all">ALL BRANDS</span></div></div></section>
  </main><footer className="landing-footer"><span>© 2026 TCC Finance</span><span>Secure operational finance platform</span></footer>
 </div>
}

export default function DashboardPage(){
 const router=useRouter(); const [ready,setReady]=useState(false); const [role,setRole]=useState(''); const [data,setData]=useState<any>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 useEffect(()=>{setRole(getAuthRole());setReady(true);},[]);
 useEffect(()=>{if(!ready||!role)return; setLoading(true);api.getDashboard().then(setData).catch(e=>setError(e instanceof Error?e.message:'Gagal memuat dashboard')).finally(()=>setLoading(false));},[ready,role]);
 if(!ready)return <div className="landing-loading"><span className="spinner"/>Memuat workspace…</div>;
 if(!role)return <Landing/>;
 const saldo=Number(data?.saldo||0), income=Number(data?.total_income||0), expense=Number(data?.total_expense||0), net=income-expense;
 return <div><div className="page-header"><div><div className="eyebrow">Overview · {role==='SUPER_ADMIN'?'All Brands':'Assigned Workspace'}</div><h1>Command Center</h1><p className="subtitle">Ringkasan finansial dan operasional dalam satu tampilan.</p></div><div className="actions"><span className="live-pill"><span className="status-dot"/> {role==='SUPER_ADMIN'?'Full access':'Assigned access'}</span><button className="btn secondary" onClick={()=>router.refresh()}>↻ Refresh</button></div></div>
 {error&&<div className="alert">⚠ {error}</div>}
 <section className="hero-grid"><div className="hero-card"><div className="hero-top"><div><div className="eyebrow">Total cash balance</div><span className="hero-label">Saldo tersedia lintas workspace</span></div><span className="hero-chip">LIVE</span></div><div className="hero-value">{formatRupiah(saldo)}</div><div className="hero-bottom"><span><i className="positive-dot"/> Data tersinkron</span><span>{data?.jumlah_transaksi||0} transaksi</span><span>{data?.jumlah_event||0} event</span></div></div><div className="quick-panel"><div className="eyebrow">Quick actions</div><div className="quick-actions"><button onClick={()=>router.push('/transactions')}><b>↕</b><span>Transaksi</span></button><button onClick={()=>router.push('/requests')}><b>✓</b><span>Pengajuan</span></button><button onClick={()=>router.push('/events')}><b>◆</b><span>Event Hub</span></button><button onClick={()=>router.push('/cash')}><b>₽</b><span>Kas & Brand</span></button></div></div></section>
 <div className="grid metric-grid"><Card icon="₽" label="Saldo" value={formatRupiah(saldo)}/><Card icon="↗" label="Total pemasukan" value={formatRupiah(income)}/><Card icon="↘" label="Total pengeluaran" value={formatRupiah(expense)}/><Card icon="◆" label="Net movement" value={formatRupiah(net)}/></div>
 <section className="section"><div className="section-head"><div><div className="eyebrow">Live snapshot</div><h2>Operational overview</h2></div></div><div className="overview-strip"><div><span>Events</span><strong>{data?.jumlah_event||0}</strong><small>active & recorded</small></div><div><span>Transactions</span><strong>{data?.jumlah_transaksi||0}</strong><small>ledger records</small></div><div><span>Net movement</span><strong className={net>=0?'income-text':'expense-text'}>{formatRupiah(net)}</strong><small>income minus expense</small></div><div><span>Access</span><strong>{role==='SUPER_ADMIN'?'GLOBAL':'ASSIGNED'}</strong><small>{role==='SUPER_ADMIN'?'all brands':'permission scope'}</small></div></div></section>
 </div>
}
