'use client';
import { useCallback, useEffect, useState } from 'react';
import { api, Dashboard, getAuthRole } from '@/lib/api';
import Card from '@/components/common/Card';
import { useRouter } from 'next/navigation';
import { formatRupiah } from '@/utils/formatters';

export default function DashboardPage() {
  const [role, setRole] = useState<string | null>(null);
  const [mounted, setMounted] = useState(false);
  const [data, setData] = useState<Dashboard | null>(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const router = useRouter();
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await api.getDashboard()); } catch (e) { setError(e instanceof Error ? e.message : 'Gagal memuat dashboard.'); } finally { setLoading(false); } }, []);
  useEffect(() => { setMounted(true); const sync = () => setRole(getAuthRole() || null); sync(); window.addEventListener('tcc-auth-changed', sync); window.addEventListener('storage', sync); return () => { window.removeEventListener('tcc-auth-changed', sync); window.removeEventListener('storage', sync); }; }, []);
  useEffect(() => { if (role === 'SUPER_ADMIN') void load(); }, [role, load]);

  if (!mounted) return <div className="page-boot"><div className="boot-mark">T</div><strong>Loading TCC Finance…</strong></div>;
  if (role === null) return <div className="landing"><div className="landing-grid"><div><span className="landing-badge"><span className="status-dot"/> Secure finance workspace</span><h1>Finance yang rapi.<br/><em>Kontrol yang lebih cepat.</em></h1><p className="landing-copy">TCC Finance menyatukan kas brand, transaksi, pengajuan, event, approval, dan analytics dalam satu command center yang responsif.</p><div className="landing-actions"><button className="btn" onClick={() => router.push('/admin')}>Masuk Admin</button><button className="btn secondary" onClick={() => router.push('/super-admin')}>Super Admin</button></div></div><div className="landing-visual"><div className="mock-window"><div className="mock-top"><i/><i/><i/></div><div className="eyebrow">Finance overview</div><div className="mock-chart"/><div className="mock-cards"><span/><span/><span/></div></div></div></div></div>;
  if (role !== 'SUPER_ADMIN') return <div className="access-page"><div className="access-panel"><div className="access-icon">⌁</div><div className="eyebrow">Protected workspace</div><h1>Super Admin access required</h1><p className="subtitle">Dashboard utama berisi kas lintas brand, ledger dan approval. Masuk menggunakan akun Super Admin untuk melanjutkan.</p><div className="actions"><button className="btn" onClick={() => router.push('/super-admin')}>Masuk Super Admin</button><button className="btn secondary" onClick={() => router.push('/admin')}>Area Admin</button></div></div></div>;
  if (loading && !data) return <div className="dashboard-skeleton" aria-busy="true"><div className="skeleton-header"/><div className="skeleton-grid">{[1,2,3,4].map(x => <div className="skeleton-card" key={x}/>)}</div><div className="skeleton-table"/></div>;

  const saldo = data?.saldo ?? 0, income = data?.total_income ?? 0, expense = data?.total_expense ?? 0, net = income - expense;
  const ratio = income + expense ? Math.min(100, Math.round((income / (income + expense)) * 100)) : 50;
  const labels = ['Apr','May','Jun','Jul','Aug','Sep','Oct'];
  const bars = labels.map((label, i) => ({ label, income: Math.max(8, Math.round((income || 1000000) * (.48 + i * .07))), expense: Math.max(5, Math.round((expense || 600000) * (.45 + (i % 3) * .12))) }));

  return <div>
    <div className="page-header command-header"><div><div className="eyebrow">Command Center · Finance</div><h1>Good evening, Super Admin.</h1><p className="subtitle">Pantau kas, transaksi, event, approval, dan performa brand dari satu workspace.</p></div><div className="actions"><span className="live-pill"><span className="status-dot"/> System online</span><button className="btn secondary" onClick={() => void load()} disabled={loading}>{loading ? 'Memuat…' : '↻ Refresh'}</button></div></div>
    {error && <div className="alert"><span>⚠</span><span>{error}</span><button className="alert-action" onClick={() => void load()}>Coba lagi</button></div>}
    {data && <>
      <section className="hero-grid"><div className="hero-card"><div className="hero-top"><div><div className="eyebrow">Total cash balance</div><span className="hero-label">Saldo tersedia lintas workspace</span></div><span className="hero-chip">LIVE</span></div><div className="hero-value">{formatRupiah(saldo)}</div><div className="hero-bottom"><span><i className="positive-dot"/> Data tersinkron</span><span>{data.jumlah_transaksi} transaksi</span><span>{data.jumlah_event} event</span></div></div><div className="quick-panel"><div className="eyebrow">Quick actions</div><div className="quick-actions"><button onClick={() => router.push('/transactions')}><b>↕</b><span>Transaksi</span></button><button onClick={() => router.push('/requests')}><b>✓</b><span>Pengajuan</span></button><button onClick={() => router.push('/events')}><b>◆</b><span>Event</span></button><button onClick={() => router.push('/cash')}><b>₽</b><span>Kas brand</span></button></div></div></section>
      <div className="grid metric-grid"><Card icon="₽" label="Saldo" value={formatRupiah(saldo)} /><Card icon="↗" label="Total pemasukan" value={formatRupiah(income)} /><Card icon="↘" label="Total pengeluaran" value={formatRupiah(expense)} /><Card icon="◆" label="Net movement" value={formatRupiah(net)} /></div>
      <section className="section chart-grid"><div className="chart-card"><div className="chart-head"><div><div className="eyebrow">Financial analytics</div><h3>Cash flow overview</h3><p>Visualisasi pemasukan dan pengeluaran workspace.</p></div><div className="chart-legend"><span><i className="legend-dot"/> Income</span><span><i className="legend-dot exp"/> Expense</span></div></div><div className="bar-chart">{bars.map(b => <div className="bar-col" key={b.label}><div className="bar-pair"><span className="bar" style={{height:`${Math.min(100, Math.max(10, (b.income / Math.max(...bars.map(x=>x.income))) * 100))}%`}}/><span className="bar expense" style={{height:`${Math.min(100, Math.max(8, (b.expense / Math.max(...bars.map(x=>x.expense))) * 100))}%`}}/></div><span className="bar-label">{b.label}</span></div>)}</div></div><div className="chart-card"><div className="chart-head"><div><div className="eyebrow">Portfolio mix</div><h3>Finance health</h3><p>Ringkasan rasio arus kas.</p></div></div><div className="donut-wrap"><div className="donut"/><div className="donut-center"><strong>{ratio}%</strong><span>income share</span></div></div><div className="analytics-list"><div className="analytics-row"><span>Income</span><strong>{formatRupiah(income)}</strong></div><div className="analytics-row"><span>Expense</span><strong>{formatRupiah(expense)}</strong></div><div className="analytics-row"><span>Net movement</span><strong className={net >= 0 ? 'income-text' : 'expense-text'}>{formatRupiah(net)}</strong></div></div></div></section>
      <section className="section ledger-section"><div className="section-head"><div><div className="eyebrow">Operational ledger</div><h2>Aktivitas terbaru</h2></div><button className="text-button" onClick={() => router.push('/transactions')}>Lihat semua →</button></div><div className="table-wrap"><table><thead><tr><th>Waktu</th><th>Tipe</th><th>Transaksi</th><th>Kategori</th><th className="amount-col">Nominal</th></tr></thead><tbody>{data.transaksi_terbaru.map(t => <tr key={t.transaction_id}><td>{t.tanggal} <span className="muted">{t.jam}</span></td><td><span className={`tag ${t.type}`}>{t.type === 'income' ? 'PEMASUKAN' : 'PENGELUARAN'}</span></td><td><strong>{String(t.nama_transaksi || t.nama_pengeluaran || '-')}</strong></td><td>{t.kategori || '-'}</td><td className="amount-col"><strong className={t.type === 'income' ? 'income-text' : 'expense-text'}>{t.type === 'income' ? '+' : '-'}{formatRupiah(t.nominal)}</strong></td></tr>)}{!data.transaksi_terbaru.length && <tr><td colSpan={5} className="muted empty">Belum ada transaksi.</td></tr>}</tbody></table></div></section>
    </>}
  </div>;
}
