'use client';
import { useState } from 'react';
import { useEscapeKey } from '@/hooks/useEscapeKey';
import { useConfirm } from '@/hooks/useConfirm';
import { useEvents } from '@/hooks/useEvents';
import EventForm from '@/components/events/components/EventForm';
import EventList from '@/components/events/components/EventList';
import ErrorMessage from '@/components/events/components/ErrorMessage';
import { getAuthRole } from '@/lib/api';
export default function EventsPage(){const {events,brands,error,setError,form,setForm,submitting,loading,submitEvent,deleteEvent,refresh}=useEvents();const [showForm,setShowForm]=useState(false);const role=getAuthRole();useEscapeKey(showForm,()=>setShowForm(false));const {confirm,ConfirmDialog}=useConfirm();const askDelete=async(id:string)=>{if(await confirm({title:'Hapus event',message:'Event ini akan dihapus permanen dan tidak bisa dikembalikan.',confirmLabel:'Hapus'}))await deleteEvent(id)};return <div><div className="page-header"><div><div className="eyebrow">Operations · Universal Event Hub</div><h1>Event Hub</h1><p className="subtitle">Kelola event lintas game, kategori, jumlah tim, registrasi, budget dan prize pool dalam satu workspace.</p></div><div className="actions"><span className="live-pill"><span className="status-dot"/>{role==='SUPER_ADMIN'?'Super Admin · Full access':'Admin · Assigned access'}</span><button className="btn secondary" onClick={()=>void refresh()} disabled={loading}>↻ Refresh</button><button className="btn" onClick={()=>setShowForm(true)}>＋ {role==='SUPER_ADMIN'?'Buat Event':'Ajukan Event'}</button></div></div><ErrorMessage message={error} onClose={()=>setError('')}/><section className="event-toolbar"><div className="event-stats"><div><span>Total event</span><strong>{events.length}</strong></div><div><span>Upcoming</span><strong>{events.filter(x=>['upcoming','UPCOMING'].includes(x.status)).length}</strong></div><div><span>Budget</span><strong>{new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(events.reduce((s,x)=>s+Number(x.budget||0),0))}</strong></div></div><div className="helper">Super Admin dapat membuka dan mengelola seluruh event. Admin dibatasi berdasarkan akses brand.</div></section><EventList events={events} onDelete={askDelete} loading={loading} canDelete={role==='SUPER_ADMIN'}/>{showForm&&<><button className="drawer-backdrop" onClick={()=>setShowForm(false)} aria-label="Tutup"/><aside className="form-drawer event-drawer"><div className="form-drawer-head"><div><div className="eyebrow">{role==='SUPER_ADMIN'?'Event Builder':'Event Request'}</div><h2>{role==='SUPER_ADMIN'?'Buat Event Baru':'Ajukan Event Baru'}</h2><p className="subtitle">{role==='SUPER_ADMIN'?'Event akan langsung masuk ke workspace.':'Pengajuan akan dikirim ke Super Admin untuk diperiksa dan disetujui.'}</p></div><button className="icon-button" onClick={()=>setShowForm(false)}>×</button></div><EventForm mode={role==='SUPER_ADMIN'?'create':'request'} form={form} setForm={setForm} onSubmit={async f=>{await submitEvent(f);setShowForm(false)}} submitting={submitting} brands={brands}/></aside></>}{ConfirmDialog}</div>}
