'use client';
import { useEffect, useState } from 'react';
import { api, Brand, FinanceRequest, Transaction, EventItem, CashAccount, saveAuthSession, clearSuperAdminSession, getSuperAdminToken, getSuperAdminEmail, getAuthRole } from '@/lib/api';
import { formatRupiah } from '@/utils/formatters';
import { useConfirm } from '@/hooks/useConfirm';

function Login(){
 const [email,setEmail]=useState('superadmin@tcc.local');
 const [password,setPassword]=useState('');
 const [error,setError]=useState('');
 const [loading,setLoading]=useState(false);
 async function submit(e:React.FormEvent){
  e.preventDefault(); setLoading(true); setError('');
  try{const r=await api.login(email,password); if(r.role!=='SUPER_ADMIN'){throw new Error('Akun ini adalah Admin biasa. Super Admin wajib login dengan akun Super Admin.');} saveAuthSession(r.token,r.email,r.role,r.user_id,r.user_name,!!r.must_change_password); window.location.href = r.must_change_password ? '/change-password' : '/super-admin';}
  catch(e){setError(e instanceof Error?e.message:'Login gagal');}
  finally{setLoading(false);}
 }
 return <div className="auth-wrap"><div className="auth-card">
  <div className="eyebrow">Restricted Area</div><h1>Super Admin Login</h1>
  <p className="subtitle">Approval, transaksi, event, brand, kas, dan konfigurasi hanya tersedia untuk Super Admin.</p>
  {error&&<div className="alert" role="alert">{error}</div>}
  <form className="form-grid" onSubmit={submit}>
   <label>Email<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label>
   <label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>
   <div className="wide"><button className="btn" disabled={loading}>{loading?'Memeriksa…':'Login Super Admin'}</button></div>
  </form>
  <p className="helper">Gunakan kredensial Super Admin yang sudah dikonfigurasi di Apps Script. Password tidak ditanam di frontend.</p>
 </div></div>
}

export default function SuperAdminPage(){
 const [logged,setLogged]=useState(false);const [loading,setLoading]=useState(true);const [req,setReq]=useState<FinanceRequest[]>([]);const [brands,setBrands]=useState<Brand[]>([]);const [tx,setTx]=useState<Transaction[]>([]);const [events,setEvents]=useState<EventItem[]>([]);const [cash,setCash]=useState<CashAccount[]>([]);const [msg,setMsg]=useState('');const [wa,setWa]=useState('');const [brandName,setBrandName]=useState('');const [saldo,setSaldo]=useState('');const [editingTx,setEditingTx]=useState<Transaction|null>(null);const [editingEvent,setEditingEvent]=useState<EventItem|null>(null);const [currentPw,setCurrentPw]=useState('');const [newPw,setNewPw]=useState('');const [adminEmail,setAdminEmail]=useState('');const [adminPassword,setAdminPassword]=useState('');const [busyReq,setBusyReq]=useState<string|null>(null);const {confirm,ConfirmDialog}=useConfirm();
 useEffect(()=>{
  const token=getSuperAdminToken();
  if(!token || getAuthRole()!=='SUPER_ADMIN'){setLogged(false);setLoading(false);return;}
  api.session().then(s=>{if(s.role==='SUPER_ADMIN')setLogged(true);else throw new Error('Bukan Super Admin')}).catch(()=>{clearSuperAdminSession();setLogged(false)}).finally(()=>setLoading(false));
},[]);
 async function load(){setLoading(true);try{const [r,b,t,e,c,cfg]=await Promise.all([api.getRequests({status:'PENDING'}),api.getBrands(),api.getTransactions(),api.getEvents(),api.getCash(),api.getConfig()]);setReq(r);setBrands(b);setTx(t);setEvents(e);setCash(c);setWa(cfg.whatsapp_number || '')}catch(e){setMsg(e instanceof Error?e.message:'Gagal memuat panel')}finally{setLoading(false)}}
 useEffect(()=>{if(logged)void load()},[logged]);
 if(!logged&&!loading)return <Login/>; if(!logged)return <div className="loading"><span className="spinner"/>Memeriksa sesi…</div>;
 async function approve(id:string,status:'APPROVED'|'REJECTED'){if(busyReq)return;setBusyReq(id);try{const r=await api.approveRequest(id,status);setMsg(status==='APPROVED'?(r.whatsapp_url?'Pengajuan disetujui. WhatsApp siap dibuka requester.':'Pengajuan disetujui.'):'Pengajuan ditolak.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Gagal memproses')}finally{setBusyReq(null)}}
 async function createBrand(e:React.FormEvent){e.preventDefault();try{const r:any=await api.createBrand({nama_brand:brandName});await api.setupCash({brand_id:r.brand_id,saldo_awal:Number(saldo),saldo_aktual:Number(saldo)});setBrandName('');setSaldo('');setMsg('Brand dan saldo awal dibuat.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Gagal membuat brand')}}
 async function editTx(){if(!editingTx)return;try{await api.updateTransaction(editingTx.type,editingTx.transaction_id,{nominal:Number(editingTx.nominal),kategori:editingTx.kategori,catatan:editingTx.catatan});setEditingTx(null);setMsg('Transaksi diperbarui.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Gagal mengubah transaksi')}}
 async function deleteTx(t:Transaction){if(!(await confirm({title:'Hapus transaksi',message:'Transaksi ini akan dihapus permanen dan tidak bisa dikembalikan.'})))return;try{await api.deleteTransaction(t.type,t.transaction_id);setMsg('Transaksi dihapus.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Gagal menghapus')}}
 async function editEv(){if(!editingEvent)return;try{await api.updateEvent(editingEvent.event_id,{nama_event:editingEvent.nama_event,game:editingEvent.game,budget:Number(editingEvent.budget),prize_pool:Number(editingEvent.prize_pool),status:editingEvent.status});setEditingEvent(null);setMsg('Event diperbarui.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Gagal mengubah event')}}
 async function deleteEv(id:string){if(!(await confirm({title:'Hapus event',message:'Event ini akan dihapus permanen dan tidak bisa dikembalikan.'})))return;try{await api.deleteEvent(id);setMsg('Event dihapus.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Gagal menghapus event')}}
 async function saveWa(){try{await api.setConfig(wa);setMsg('Nomor WhatsApp tersimpan.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Gagal menyimpan WhatsApp')}}
 async function createAdmin(e:React.FormEvent){e.preventDefault();try{await api.createAdmin({email:adminEmail,password:adminPassword,nama:adminEmail});setAdminEmail('');setAdminPassword('');setMsg('Akun Admin berhasil dibuat.')}catch(e){setMsg(e instanceof Error?e.message:'Gagal membuat admin')}}
 async function changePassword(e:React.FormEvent){e.preventDefault();try{await api.changePassword(currentPw,newPw);setCurrentPw('');setNewPw('');setMsg('Password berhasil diganti.')}catch(e){setMsg(e instanceof Error?e.message:'Gagal mengganti password')}}
 async function logout(){await api.logout().catch(()=>{});clearSuperAdminSession();location.reload()}
 return <div><div className="page-header"><div><div className="eyebrow">Restricted Control Center</div><h1>Super Admin</h1><p className="subtitle">Login: {getSuperAdminEmail()} • hanya role ini yang dapat mengubah/menghapus data.</p></div><div className="actions"><button className="btn secondary" onClick={()=>void load()}>↻ Refresh</button><button className="btn secondary" onClick={()=>void logout()}>Logout</button></div></div>{msg&&<div className="alert">{msg}</div>}
 <section className="section"><div className="section-head"><h2>Approval Center</h2><span className="muted">{req.length} pending</span></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Jenis</th><th>Nama</th><th>Brand</th><th>Pengaju</th><th>Aksi</th></tr></thead><tbody>{req.map(r=><tr key={r.request_id}><td data-label="ID">{r.request_id}</td><td data-label="Jenis">{r.type}</td><td data-label="Nama">{r.nama}</td><td data-label="Brand">{brands.find(b=>b.brand_id===r.brand_id)?.nama_brand||r.brand_id}</td><td data-label="Pengaju">{r.user_name}</td><td data-label="Aksi">{busyReq===r.request_id?<span className="muted"><span className="spinner"/> Memproses…</span>:<><button className="btn" onClick={()=>void approve(r.request_id,'APPROVED')} disabled={!!busyReq}>ACC</button> <button className="btn secondary" onClick={()=>void approve(r.request_id,'REJECTED')} disabled={!!busyReq}>Tolak</button></>}</td></tr>)}{!req.length&&<tr><td colSpan={6} className="empty muted">Tidak ada pengajuan pending.</td></tr>}</tbody></table></div></section>
 <section className="section"><div className="section-head"><h2>WhatsApp Approval</h2><span className="muted">Nomor disimpan di Script Properties</span></div><div className="form-grid"><label>Nomor WhatsApp TCC<input placeholder="62812xxxxxxxx" value={wa} onChange={e=>setWa(e.target.value)}/><span className="helper">Gunakan format internasional tanpa +.</span></label><div><button className="btn" onClick={()=>void saveWa()}>Simpan Nomor</button></div></div></section>
 <section className="section"><div className="section-head"><h2>Brand & Saldo Awal</h2></div><form className="form-grid" onSubmit={createBrand}><label>Nama brand<input value={brandName} onChange={e=>setBrandName(e.target.value)} required/></label><label>Saldo awal<input type="number" min="0" value={saldo} onChange={e=>setSaldo(e.target.value)} required/></label><div><button className="btn">Tambah Brand</button></div></form><div className="grid">{cash.map(c=><div className="card" key={c.brand_id}><div className="eyebrow">{c.nama_brand}</div><div className="card-value">{formatRupiah(c.saldo_sistem)}</div><div className="muted">Aktual {formatRupiah(c.saldo_aktual)}</div></div>)}</div></section>
 <section className="section"><div className="section-head"><h2>Transaksi — Super Admin Only</h2><span className="muted">Edit/hapus hanya di console ini</span></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Tipe</th><th>Nama</th><th>Kategori</th><th>Nominal</th><th>Aksi</th></tr></thead><tbody>{tx.map(t=><tr key={t.transaction_id}><td data-label="ID">{t.transaction_id}</td><td data-label="Tipe">{t.type}</td><td data-label="Nama">{String(t.nama_transaksi||t.nama_pengeluaran)}</td><td data-label="Kategori">{t.kategori}</td><td data-label="Nominal">{formatRupiah(t.nominal)}</td><td data-label="Aksi"><button className="btn secondary" onClick={()=>setEditingTx(t)}>Edit</button> <button className="btn secondary" onClick={()=>void deleteTx(t)}>Hapus</button></td></tr>)}{!tx.length&&<tr><td colSpan={6} className="empty muted">Belum ada transaksi.</td></tr>}</tbody></table></div>{editingTx&&<div className="panel"><h3>Edit Transaksi</h3><div className="form-grid"><label>Kategori<input value={editingTx.kategori} onChange={e=>setEditingTx({...editingTx,kategori:e.target.value})}/></label><label>Nominal<input type="number" value={String(editingTx.nominal)} onChange={e=>setEditingTx({...editingTx,nominal:Number(e.target.value)})}/></label><label className="wide">Catatan<textarea value={editingTx.catatan||''} onChange={e=>setEditingTx({...editingTx,catatan:e.target.value})}/></label><div><button className="btn" onClick={()=>void editTx()}>Simpan</button> <button className="btn secondary" onClick={()=>setEditingTx(null)}>Batal</button></div></div></div>}</section>
 <section className="section"><div className="section-head"><h2>Event — Super Admin Only</h2></div><div className="table-wrap"><table><thead><tr><th>Event</th><th>Game</th><th>Budget</th><th>Prize</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{events.map(e=><tr key={e.event_id}><td data-label="Event">{e.nama_event}</td><td data-label="Game">{e.game}</td><td data-label="Budget">{formatRupiah(e.budget)}</td><td data-label="Prize">{formatRupiah(e.prize_pool)}</td><td data-label="Status">{e.status}</td><td data-label="Aksi"><button className="btn secondary" onClick={()=>setEditingEvent(e)}>Edit</button> <button className="btn secondary" onClick={()=>void deleteEv(e.event_id)}>Hapus</button></td></tr>)}{!events.length&&<tr><td colSpan={6} className="empty muted">Belum ada event.</td></tr>}</tbody></table></div>{editingEvent&&<div className="panel"><h3>Edit Event</h3><div className="form-grid"><label>Nama<input value={editingEvent.nama_event} onChange={e=>setEditingEvent({...editingEvent,nama_event:e.target.value})}/></label><label>Game<input value={editingEvent.game} onChange={e=>setEditingEvent({...editingEvent,game:e.target.value})}/></label><label>Budget<input type="number" value={String(editingEvent.budget)} onChange={e=>setEditingEvent({...editingEvent,budget:Number(e.target.value)})}/></label><label>Prize Pool<input type="number" value={String(editingEvent.prize_pool)} onChange={e=>setEditingEvent({...editingEvent,prize_pool:Number(e.target.value)})}/></label><label>Status<input value={editingEvent.status} onChange={e=>setEditingEvent({...editingEvent,status:e.target.value})}/></label><div><button className="btn" onClick={()=>void editEv()}>Simpan</button> <button className="btn secondary" onClick={()=>setEditingEvent(null)}>Batal</button></div></div></div>}</section>
 <section className="section"><div className="section-head"><h2>Manajemen Admin</h2><span className="muted">Buat akun admin tanpa akses edit ledger</span></div><form className="form-grid" onSubmit={createAdmin}><label>Email Admin<input type="email" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)} placeholder="admin@brand.com" required/></label><label>Password Sementara<input type="password" minLength={12} value={adminPassword} onChange={e=>setAdminPassword(e.target.value)} placeholder="Minimal 12 karakter" required/></label><div className="wide"><button className="btn">+ Buat Akun Admin</button></div></form></section><section className="section"><div className="section-head"><h2>Keamanan Akun</h2></div><form className="form-grid" onSubmit={changePassword}><label>Password lama<input type="password" value={currentPw} onChange={e=>setCurrentPw(e.target.value)} required/></label><label>Password baru<input type="password" value={newPw} onChange={e=>setNewPw(e.target.value)} minLength={12} required/></label><div><button className="btn">Ganti Password</button></div></form></section>{ConfirmDialog}
 </div>
}
