'use client';
import { useCallback, useEffect, useState } from 'react';
import { api, CashAccount, getAuthRole } from '@/lib/api';
import { formatRupiah } from '@/utils/formatters';
import { useEscapeKey } from '@/hooks/useEscapeKey';

export default function CashPage(){
 const [role,setRole]=useState(''); const [cash,setCash]=useState<CashAccount[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [selected,setSelected]=useState<CashAccount|null>(null); const [actual,setActual]=useState(''); const [note,setNote]=useState(''); const [busy,setBusy]=useState(false);
 useEscapeKey(!!selected,()=>setSelected(null));
 const load=useCallback(async()=>{setLoading(true);setError('');try{setCash(await api.getCash())}catch(e){setError(e instanceof Error?e.message:'Gagal memuat kas')}finally{setLoading(false)}},[]);
 useEffect(()=>{setRole(getAuthRole());void load()},[load]);
 const isSuper=role==='SUPER_ADMIN';
 async function adjust(){if(!selected)return;setBusy(true);try{await api.adjustCash({brand_id:selected.brand_id,saldo_aktual:Number(actual.replace(/[^0-9]/g,'')),catatan:note});setSelected(null);setActual('');setNote('');await load()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan rekonsiliasi')}finally{setBusy(false)}}
 const total=cash.reduce((s,x)=>s+Number(x.saldo_sistem||0),0);
 return <div>
  <div className="page-header"><div><div className="eyebrow">Finance · Cash Control</div><h1>Kas & Brand</h1><p className="subtitle">Pantau saldo setiap brand. Super Admin dapat mengelola seluruh kas; Admin hanya melihat brand yang diberi akses.</p></div><div className="actions"><span className="live-pill"><span className="status-dot"/>{isSuper?'Full access':'Assigned access'}</span><button className="btn secondary" onClick={()=>void load()} disabled={loading}>↻ Refresh</button></div></div>
  {error&&<div className="alert">⚠ {error}</div>}
  <section className="cash-overview"><div className="cash-total"><span>Total visible cash</span><strong>{formatRupiah(total)}</strong><small>{cash.length} brand tersedia untuk akun ini</small></div><div className="cash-health"><span className="eyebrow">Access scope</span><strong>{isSuper?'ALL BRANDS':'ASSIGNED BRANDS'}</strong><small>Permission diperiksa oleh backend.</small></div></section>
  <section className="section"><div className="section-head"><div><div className="eyebrow">Brand ledger</div><h2>Saldo Kas</h2></div><span className="muted">{cash.length} akun kas</span></div>
   {loading?<div className="cash-grid">{[1,2,3].map(i=><div className="cash-card skeleton-card" key={i}/>)}</div>:<div className="cash-grid">{cash.map(c=>{const diff=Number(c.saldo_aktual||0)-Number(c.saldo_sistem||0);return <article className="cash-card" key={c.brand_id}><div className="cash-card-top"><div className="brand-avatar">{(c.nama_brand||'B').slice(0,1).toUpperCase()}</div><div><strong>{c.nama_brand}</strong><span>Brand cash account</span></div><span className={`health-dot ${diff===0?'ok':'warn'}`}/></div><div className="cash-balance">{formatRupiah(c.saldo_sistem)}</div><div className="cash-meta"><span>Saldo awal <b>{formatRupiah(c.saldo_awal)}</b></span><span>Income <b className="income-text">{formatRupiah(c.total_income)}</b></span><span>Expense <b className="expense-text">{formatRupiah(c.total_expense)}</b></span><span>Aktual <b>{formatRupiah(c.saldo_aktual)}</b></span></div><div className={`reconcile ${diff===0?'ok':'warn'}`}><span>{diff===0?'✓ Rekonsiliasi cocok':'⚠ Ada selisih'}</span><b>{formatRupiah(diff)}</b></div><div className="card-actions">{isSuper&&<button className="btn secondary" onClick={()=>{setSelected(c);setActual(String(c.saldo_aktual||0));}}>Rekonsiliasi</button>}<button className="btn secondary" onClick={()=>location.href=`/transactions?brand=${encodeURIComponent(c.brand_id)}`}>Transaksi</button></div></article>})}</div>}
  </section>
  {isSuper&&<section className="section info-panel"><div><div className="eyebrow">Super Admin</div><h2>Cash governance</h2><p>Super Admin memiliki akses mutlak ke seluruh brand, saldo, transaksi, setup dan rekonsiliasi. Semua perubahan harus melewati endpoint terproteksi dan dapat dicatat di audit log.</p></div><button className="btn" onClick={()=>location.href='/super-admin'}>Buka Administration →</button></section>}
  {selected&&<><button className="drawer-backdrop" onClick={()=>setSelected(null)} aria-label="Tutup"/><aside className="form-drawer"><div className="form-drawer-head"><div><div className="eyebrow">Cash reconciliation</div><h2>{selected.nama_brand}</h2><p className="subtitle">Cocokkan saldo aktual dengan saldo sistem.</p></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div><div className="drawer-stat"><span>Saldo sistem</span><strong>{formatRupiah(selected.saldo_sistem)}</strong></div><label>Saldo aktual<input inputMode="numeric" value={actual?formatRupiah(Number(actual.replace(/[^0-9]/g,''))):''} onChange={e=>setActual(e.target.value.replace(/[^0-9]/g,''))}/></label><label>Catatan<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Alasan rekonsiliasi..."/></label><button className="btn" onClick={()=>void adjust()} disabled={busy}>{busy?'Menyimpan…':'Simpan Rekonsiliasi'}</button></aside></>}
 </div>
}
